# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductData'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
