# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170630_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_object',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductData'),
        ),
    ]
