# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170630_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
