# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170630_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='measured_unit',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
