# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_measured_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
