# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20170701_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.CharField(default='/media/welcome/Veg_World.png', max_length=500, null=True),
        ),
    ]
