# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20170702_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.FloatField(default=0.0),
        ),
    ]
