# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=10, default=56.0, max_digits=100),
        ),
    ]
