# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170702_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.FloatField(default=10),
        ),
    ]
