# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20170702_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cost_price',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_units',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_product_data',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_product_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='noname', max_length=500),
        ),
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.CharField(default='Kg', max_length=100),
        ),
    ]
