# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchase_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='size',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.CharField(default='0Kg', max_length=100),
        ),
    ]
