# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20170707_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cost_price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
