# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_order', '0006_auto_20170618_1651'),
        ('inventory', '0024_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('orderdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_order.OrderData')),
            ],
        ),
    ]
