# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='units',
            field=models.FloatField(default=0),
        ),
    ]
