# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_purchaseproduct_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='units_left_to_be_sold',
            field=models.FloatField(default=0),
        ),
    ]
