# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_purchaseproduct_units_left_to_be_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
